### ISSUE TITLE
Jieshuo performance 

### ISSUE THREAD

**Issue by Nalryn** [arutar/FrankenDriver#1]
3d marks drop from 2350 to 2050 utilizing drivers prescribed vs what jieshuo prescribed as 9 month old drivers. any suggestions? 2d benchmark rose from 613 to 670. same jieshuo 3070m.

**Comment by Nalryn** [comment]
less that 1 fps playing 7 days to die. hook me up with how to fix this with your drivers. cause the chinese drivers actually played full 60fps capped. and you stated yours were better.

**Comment by arutar** [comment]
I tested the performance of Chinese and original drivers at my stand. It seems that performance jumps from one driver version to another. This is due to the fact that the nvidia developers are constantly improving the driver. In the Frankendriver project, there is no modification of the original driver from Nvidia and you get the performance that was laid down by the Nvidia developers. Added driver version 512.95 which, according to my tests, turned out to be a little more productive than the Chinese one.
![1](https://user-images.githubusercontent.com/116097611/208229371-e4a2475e-8cd4-447f-8851-8eafb95b9c97.png)
![2](https://user-images.githubusercontent.com/116097611/208229374-a46ceabf-71e7-44e3-84e0-f99078214e71.png)
![3](https://user-images.githubusercontent.com/116097611/208229376-07e8c340-1233-4294-a9c3-6904eec618ba.png)
